# Image name: landerlini/pylamarr:dev
FROM python:3.11.8

RUN pip install --root-user-action=ignore \
        pandas \
        "numpy<2.0" \
        pyarrow \
        "uproot>=4" \
        "tqdm" \
        SQLamarr \
        "tensorflow<=2.14" \
        pydantic \
        requests \
        particle \
        ipython \
        ipykernel \
        pyyaml \
        "scikit-learn==1.3.2"